language: "Croatian"
translation_mapping:
  "the personality of God": "ličnost Boga"
  "trinitarian": "trinitarijanski"
  "nontrinitarian": "netrinitarijanski"
  "creed": "kredo"
  "fundamental principles": "fundamentalni principi"
  "foundational principles": "temeljni principi"
  "Calvary": "Golgota"
bible_verse_translation: "Varaždinska Biblija HBN"
speaker_gender: "male"
additional_settings:
  - "Please ignore filler words if they are not necessary for the meaning of the sentence"